"use client"

import {  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { useLanguage } from "@/context/translate";
import '../../../app/globals.css'

export default function AccordionExperience() {
    const { isEnglish } = useLanguage();

  return (
    <Accordion type="single" collapsible className="px-2 rounded-xl bgAccordion">
      <AccordionItem value="item-1" className="border-b-0">
        <AccordionTrigger>{isEnglish ? "View more" : "Ver más"}</AccordionTrigger>
        <AccordionContent className="text-base">
            <p className="mb-5">{isEnglish ? "Administrators can generate monthly reports for client companies through the integration of ChatGPT artificial intelligence. From the clients' perspective, the platform offers an intuitive and accessible user experience, allowing them to view and analyze the reports generated by the administrators." : "Los administradores pueden generar reportes mensuales de las empresas clientas mediante la integración de inteligencia artificial ChatGPT y desde la perspectiva de los clientes, la plataforma ofrece una experiencia de usuario intuitiva y accesible, permitiéndoles visualizar y analizar los informes generados por los administradores."}</p>
            <p><span className='font-medium text-lg bg-gradient-to-r from-[#F1FF4D] to-[#3ECF8E] bg-clip-text text-transparent'>{isEnglish ? "My tasks" : "Mis tareas"}</span> <br /> { isEnglish ? "In this project, I handle various essential tasks, such as the design and development of the user interface for the entire platform. This includes creating a visually appealing and easy-to-navigate environment that enhances the user experience. I also perform complex interactions with the database to enable different site functionalities, ensuring that information is managed and presented efficiently. Additionally, I have integrated forms that allow the upload of various types of files, such as images and PDF documents, thus facilitating the incorporation and management of important documents by the users." : "En este proyecto, me encargo de diversas tareas esenciales, como el diseño y desarrollo de la interfaz de usuario para toda la plataforma. Esto incluye crear un entorno visualmente atractivo y fácil de navegar que mejore la experiencia del usuario. También realizo interacciones complejas con la base de datos para habilitar distintas funcionalidades del sitio, asegurando que la información sea gestionada y presentada de manera eficiente. Además, he integrado formularios que permiten la carga de diversos tipos de archivos, como imágenes y documentos PDF, facilitando así la incorporación y gestión de documentos importantes por parte de los usuarios."}</p>
        </AccordionContent>
      </AccordionItem>
    </Accordion>
  );
}
