"use client"

import Carrusel from '@/components/Carrusel';
import React from 'react'
import TechnologyBox from '../TechnologyBox';
import TypescriptIcon from '@/components/icons/TypescriptIcon';
import NextIcon from '@/components/icons/NextIcon';
import TailwindIcon from '@/components/icons/TailwindIcon';
import WebIcon from '@/components/icons/WebIcon';
import Link from 'next/link';
import MexicoIcon from '@/components/icons/MexicoIcon';
import { useLanguage } from '@/context/translate';
import Image from 'next/image';
import tualo from './dashboard-tualo.png'
import SupabaseIcon from '@/components/icons/SupabaseIcon';
import ChatGPTIcon from '@/components/icons/ChatGPTIcon';
import NodeIcon from '@/components/icons/NodeIcon';

const TualoDashboard = () => {
    const { isEnglish } = useLanguage();
    return (
      <div className="flex flex-col gap-3">
        <div className="flex items-center text-white font-medium text-2xl gap-2">
            Tualo
          <MexicoIcon />
        </div>
  
          <span className="bg-gradient-to-r from-[#F1FF4D] to-[#3ECF8E] bg-clip-text text-transparent font-medium text-2xl">Desarrollador Fullstack</span>
        <div>
          <p className="text-white font-medium text-lg">Abril 2024 - Actual</p>
        </div>
        <div className="flex items-center text-white justify-between gap-24 max-lg:flex-col max-lg:gap-12">
          <div className="flex flex-col gap-3 lg:w-[60%]">
            <div>
              {isEnglish
                ? <p>This is an advanced Dashboard specifically designed for Tualo clients. This innovative platform is divided into two main sections: one for administrators and another for clients. <br /> <br /> Administrators can generate monthly reports for client companies through the integration of ChatGPT artificial intelligence, and from the clients perspective, the platform offers an intuitive and accessible user experience, allowing them to visualize and analyze the reports generated by administrators. <br /> <br /> <span className='font-medium text-lg bg-gradient-to-r from-[#F1FF4D] to-[#3ECF8E] bg-clip-text text-transparent'>{isEnglish ? "My tasks" : "Mis tareas"}</span> <br /> In this project, I am responsible for various essential tasks, such as designing and developing the user interface for the entire platform. This includes creating a visually attractive and easy-to-navigate environment that enhances the user experience. I also perform complex interactions with the database to enable various site functionalities, ensuring that the information is managed and presented efficiently. Additionally, I have integrated forms that allow the upload of various types of files, such as images and PDF documents, thus facilitating the incorporation and management of important documents by users.</p>
                : <p>Se trata de un avanzado Dashboard diseñado específicamente para los clientes de Tualo. Esta innovadora plataforma está dividida en dos secciones principales: una para administradores y otra para clientes. <br /> <br /> Los administradores pueden generar reportes mensuales de las empresas clientas mediante la integración de inteligencia artificial ChatGPT y desde la perspectiva de los clientes, la plataforma ofrece una experiencia de usuario intuitiva y accesible, permitiéndoles visualizar y analizar los informes generados por los administradores. <br /> <br /> <span className='font-medium text-lg bg-gradient-to-r from-[#F1FF4D] to-[#3ECF8E] bg-clip-text text-transparent'>{isEnglish ? "My tasks" : "Mis tareas"}</span> <br /> En este proyecto, me encargo de diversas tareas esenciales, como el diseño y desarrollo de la interfaz de usuario para toda la plataforma. Esto incluye crear un entorno visualmente atractivo y fácil de navegar que mejore la experiencia del usuario. También realizo interacciones complejas con la base de datos para habilitar distintas funcionalidades del sitio, asegurando que la información sea gestionada y presentada de manera eficiente. Además, he integrado formularios que permiten la carga de diversos tipos de archivos, como imágenes y documentos PDF, facilitando así la incorporación y gestión de documentos importantes por parte de los usuarios.</p>}
            </div>
            <div>
            <span className="bg-gradient-to-r from-[#F1FF4D] to-[#3ECF8E] bg-clip-text text-transparent font-medium text-lg">
              {isEnglish ? "My biggest challengues" : "Mis mayores desafíos"}
            </span>
            <ul className="list-disc flex flex-col gap-2">
              <li>
                {isEnglish
                  ? "Develop the user interface of the entire platform."
                  : "Llevar a cabo la interfaz de usuario de toda la plataforma."}
              </li>
              <li>
                {isEnglish
                  ? "Form integration for PDF file uploads."
                  : "Integración de formularios para la carga de archivos PDF."}
              </li>
              <li>
                {isEnglish
                  ? "Integrate a comprehensive navigation system for the entire platform flow, both for the administrative side and the client side."
                  : "Integrar un sistema de navegación completo para todo el flujo de la plataforma, tanto del lado administrativo como el del cliente."}
              </li>
            </ul>
          </div>

  
            <div className="flex flex-col gap-2 mt-4">
              <span className="bg-gradient-to-r from-[#F1FF4D] to-[#3ECF8E] bg-clip-text text-transparent font-medium text-lg">
                {isEnglish ? "Technologies" : "Tecnologías utilizadas"}
              </span>
  
              <div className="flex items-center flex-wrap gap-2">
                <TechnologyBox icon={<TypescriptIcon />} technology="Typescript"/>
                <TechnologyBox icon={<NextIcon />} technology="Next Js" />
                <TechnologyBox icon={<TailwindIcon />} technology="Tailwind css"/>
                <TechnologyBox icon={<NodeIcon />} technology="Node Js"/>
                <TechnologyBox icon={<SupabaseIcon />} technology="Supabase"/>
                <TechnologyBox icon={<ChatGPTIcon />} technology="Open AI"/>
              </div>
            </div>
          </div>
          <div className="lg:w-[50%] max-lg:px-4">
              <Image src={tualo} alt='tualo' width={1000} height={1000}/>
          </div>
        </div>
      </div>
    );
  };

export default TualoDashboard